show_drafts: true

# Accepts connections on port 4000 from any source
host: 0.0.0.0
port: 4000

# Don't compress SASS output
sass:
  style: full

# Don't send Google Analytics tracking events while running in dev mode
enable_google_analytics: false